import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import Link from "next/link";
import dynamic from "next/dynamic";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import ReactLenis from "@studio-freight/react-lenis";

const inter = Inter({ subsets: ["latin"] });
const Scene = dynamic(() => import("@/components/ui/scene"), { ssr: false });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ overscrollBehaviorY: "none" }}
        // className={GeistSans.className}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <div className="flex justify-center items-center flex-col bg-black min-h-screen">
            {/* <header className="px-4 lg:px-6 h-14 flex items-center">
              <Link className="flex items-center justify-center" href="#">
                <Logo className="h-6 w-6" />
                <span className="sr-only">pmndrs</span>
              </Link>
              <nav className="ml-auto flex gap-4 sm:gap-6">
                <Link
                  className="text-sm font-medium hover:underline underline-offset-4"
                  href="#"
                >
                  Features
                </Link>
                <Link
                  className="text-sm font-medium hover:underline underline-offset-4"
                  href="#"
                >
                  Pricing
                </Link>
                <Link
                  className="text-sm font-medium hover:underline underline-offset-4"
                  href="#"
                >
                  About
                </Link>
                <Link
                  className="text-sm font-medium hover:underline underline-offset-4"
                  href="#"
                >
                  Contact
                </Link>
              </nav>
            </header> */}
            {children}
          </div>
        </ThemeProvider>
        <Scene />
      </body>
    </html>
  );
}
